# BÀI TẬP: MEDICAL INSURANCE COST
**Nguồn:** kaggle.com/datasets/mosapabdelghany/medical-insurance-cost-dataset

## Setup

In [2]:
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
from pathlib import Path
from scipy import stats

sns.set_style('whitegrid')


csv_path = 'https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv'

df = pd.read_csv(csv_path)
print('Loaded from:', csv_path)
df.head()

Loaded from: https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

---
# PHẦN A — DATA PROFILING
## A.1. Data size, column names, data types

In [3]:
# TODO
print("số dòng:", df.shape[0], "| Số cột:", df.shape[1])
print()
df.info

số dòng: 1338 | Số cột: 7

<bound method DataFrame.info of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>

## A.2. Missing values & Duplicate data

In [4]:
# TODO
print("Số giá trị thiếu theo cột:")
print(df.isnull().sum())

print("\nTổng số giá trị thiếu:", df.isnull().sum().sum())

print("\nSố dòng trùng lặp:", df.duplicated().sum())

Số giá trị thiếu theo cột:
age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

Tổng số giá trị thiếu: 0

Số dòng trùng lặp: 1

## A.3. Invalid values

In [5]:
# TODO
print("Age nhỏ hơn 0:", (df["age"] < 0).sum())
print("BMI nhỏ hơn 0:", (df["bmi"] < 0).sum())
print("Children nhỏ hơn 0:", (df["children"] < 0).sum())
print("Charges nhỏ hơn 0:", (df["charges"] < 0).sum())

Age nhỏ hơn 0: 0
BMI nhỏ hơn 0: 0
Children nhỏ hơn 0: 0
Charges nhỏ hơn 0: 0

## A.4. Create a new column
Tạo cột `bmi_group`: Normal (<25), Overweight (25-30), Obese (>=30).

In [15]:
# TODO
def bmi_group(bmi):
    if bmi < 25:
        return "Normal"
    elif bmi < 30:
        return "Overweight"
    else:
        return "Obese"

df["bmi_group"] = df["bmi"].apply(bmi_group)

df.head()

   age     sex     bmi  children smoker     region      charges   bmi_group
0   19  female  27.900         0    yes  southwest  16884.92400  Overweight
1   18    male  33.770         1     no  southeast   1725.55230       Obese
2   28    male  33.000         3     no  southeast   4449.46200       Obese
3   33    male  22.705         0     no  northwest  21984.47061      Normal
4   32    male  28.880         0     no  northwest   3866.85520  Overweight

---
# PHẦN B — DESCRIPTIVE STATISTICS
## Group 1 — Central Tendency

In [16]:
# TODO
print("Mean:")
print(df[["age", "bmi", "children", "charges"]].mean())

print("\nMedian:")
print(df[["age", "bmi", "children", "charges"]].median())

print("\nMode:")
print(df[["age", "bmi", "children", "charges"]].mode().iloc[0])

Mean:
age            39.207025
bmi            30.663397
children        1.094918
charges     13270.422265
dtype: float64

Median:
age           39.000
bmi           30.400
children       1.000
charges     9382.033
dtype: float64

Mode:
age           18.0000
bmi           32.3000
children       0.0000
charges     1639.5631
Name: 0, dtype: float64

## Group 2 — Dispersion

In [17]:
# TODO
print("Variance:")
print(df[["age", "bmi", "children", "charges"]].var())

print("\nStandard Deviation:")
print(df[["age", "bmi", "children", "charges"]].std())

print("\nRange:")
print(df[["age", "bmi", "children", "charges"]].max()
      - df[["age", "bmi", "children", "charges"]].min())

Variance:
age         1.974014e+02
bmi         3.718788e+01
children    1.453213e+00
charges     1.466524e+08
dtype: float64

Standard Deviation:
age            14.049960
bmi             6.098187
children        1.205493
charges     12110.011237
dtype: float64

Range:
age            46.00000
bmi            37.17000
children        5.00000
charges     62648.55411
dtype: float64

## Group 3 — Location and Shape

In [18]:
# TODO
print(df[["age", "bmi", "children", "charges"]].describe())

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

---
# PHẦN C — DEFINE THE QUESTION

## Câu hỏi 1: Người hút thuốc trả chi phí cao hơn bao nhiêu lần so với người không hút, và có đồng đều giữa các vùng không?

In [19]:
# TODO
avg_smoker = df.groupby("smoker")["charges"].mean()

print(avg_smoker)

ratio = avg_smoker["yes"] / avg_smoker["no"]

print("Người hút thuốc trả cao gấp:", ratio, "lần")

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64
Người hút thuốc trả cao gấp: 3.800001458298319 lần

## Câu hỏi 2: BMI có tương quan với chi phí mạnh hơn ở nhóm hút thuốc hay không hút thuốc?

In [20]:
# TODO
smoker_corr = df[df["smoker"] == "yes"]["bmi"].corr(
    df[df["smoker"] == "yes"]["charges"]
)

non_smoker_corr = df[df["smoker"] == "no"]["bmi"].corr(
    df[df["smoker"] == "no"]["charges"]
)

print("Tương quan nhóm hút thuốc:", smoker_corr)
print("Tương quan nhóm không hút:", non_smoker_corr)

if abs(smoker_corr) > abs(non_smoker_corr):
    print("BMI tương quan mạnh hơn ở nhóm hút thuốc.")
else:
    print("BMI tương quan mạnh hơn ở nhóm không hút thuốc.")

Tương quan nhóm hút thuốc: 0.8064806070155401
Tương quan nhóm không hút: 0.0840365431283327
BMI tương quan mạnh hơn ở nhóm hút thuốc.

## Câu hỏi 3: Vùng nào có chi phí bảo hiểm trung bình cao nhất?

In [21]:
# TODO
result = df.groupby("region")["charges"].mean()

print(result)

print("\nVùng có chi phí cao nhất:")
print(result.idxmax())

region
northeast    13406.384516
northwest    12417.575374
southeast    14735.411438
southwest    12346.937377
Name: charges, dtype: float64

Vùng có chi phí cao nhất:
southeast

## Câu hỏi 4: Số lượng con cái có làm tăng chi phí bảo hiểm không?

In [22]:
# TODO
result = df.groupby("children")["charges"].mean()

print(result)

children
0    12365.975602
1    12731.171832
2    15073.563734
3    15355.318367
4    13850.656311
5     8786.035247
Name: charges, dtype: float64

## Câu hỏi 5: Tuổi có tương quan với chi phí bảo hiểm không?

In [23]:
# TODO
corr = df["age"].corr(df["charges"])

print("Tương quan giữa tuổi và chi phí:", corr)

if corr > 0:
    print("Tuổi có tương quan dương với chi phí bảo hiểm.")
elif corr < 0:
    print("Tuổi có tương quan âm với chi phí bảo hiểm.")
else:
    print("Tuổi không có tương quan với chi phí bảo hiểm.")

Tương quan giữa tuổi và chi phí: 0.29900819333064776
Tuổi có tương quan dương với chi phí bảo hiểm.

## Câu hỏi 6 (Tổng hợp) — Viết insight tổng hợp
Dựa trên Phần A, B, C, viết 4-5 câu insight tổng thể.

*(Viết insight của bạn vào đây...)*